replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/composite-silo-411620/artemis
  tag: "2.0.0"


service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  annotations: {}

  hosts:
    - host: dev-artemis.makeasyaws.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    - secretName: dev-artemis-tls
      hosts:
        - dev-artemis.makeasyaws.com